@startuml
class com.example.glutenfree.business {
- String type
- String name
- String description
- String address
- String addressCity
- String opening_hours
- String site_link
- String facebook_link
- String prices
- String delivery_services
- String phone
- String rating
- ArrayList<String> pictures
- String video
- String key
- ArrayList<String> reviews
+ <<Create>> business(String,String,String,String,String,String,String,String,String,String,String,String,ArrayList<String>,String,String,ArrayList<String>)
+ <<Create>> business()
+ String getType()
+ void setType(String)
+ String getName()
+ void setName(String)
+ String getDescription()
+ void setDescription(String)
+ String getAddress()
+ void setAddress(String)
+ String getAddressCity()
+ void setAddressCity(String)
+ String getOpening_hours()
+ void setOpening_hours(String)
+ String getSite_link()
+ void setSite_link(String)
+ String getFacebook_link()
+ void setFacebook_link(String)
+ String getPrices()
+ void setPrices(String)
+ String getDelivery_services()
+ void setDelivery_services(String)
+ String getPhone()
+ void setPhone(String)
+ String getRating()
+ void setRating(String)
+ ArrayList<String> getPictures()
+ void setPictures(ArrayList<String>)
+ String getVideo()
+ void setVideo(String)
+ String getKey()
+ void setKey(String)
+ ArrayList<String> getReviews()
+ void setReviews(ArrayList<String>)
+ String toString()
}
class com.example.glutenfree.CityData {
- String City_Name
- String id_Street
- String Street_name
+ String getCity_Name()
+ void setCity_Name(String)
+ String getStreet_name()
+ void setStreet_name(String)
+ String toString()
+ String getId_Street()
+ void setId_Street(String)
}
class com.example.glutenfree.WifiReceiver {
- WifiManager wifiManager
- ConnectivityManager cm
- NetworkInfo networkInfo
~ boolean is_wifi
- Dialog dialog
- Toolbar toolbar
+ <<Create>> WifiReceiver()
+ <<Create>> WifiReceiver(Dialog,Toolbar)
+ void onReceive(Context,Intent)
}
class com.example.glutenfree.businessAdapter {
- ArrayList<business> businessList
- Context context
+ <<Create>> businessAdapter(ArrayList<business>,Context)
+ viewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(viewHolder,int)
+ int getItemCount()
}
class com.example.glutenfree.businessAdapter.viewHolder {
~ TextView businessName
~ SliderView sliderView
~ YouTubePlayer youTubePlayerView
+ <<Create>> viewHolder(View)
}
class com.example.glutenfree.UpdateUser {
~ TextInputEditText FirstName
~ Button button
~ Switch profileType
~ FirebaseDatabase firebaseDatabase
~ DatabaseReference databaseReference
~ String firstName
~ ProgressDialog p
~ Toolbar toolbar
~ AlertDialog.Builder adb
~ AlertDialog ad
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
~ check_Input check
# void onCreate(Bundle)
+ void onClick(View)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.Profile {
~ Button button_logout
~ ImageView profileImage
~ TextView textViewUser
~ FirebaseAuth firebaseAuth
~ FirebaseDatabase firebaseDatabase
~ ProgressDialog p
~ DatabaseReference databaseReference
~ StorageReference storageReference
~ String picname
~ Uri uri
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
~ AlertDialog.Builder adb
~ AlertDialog ad
~ Toolbar toolbar
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
# void onCreate(Bundle)
+ void onClick(View)
# void onActivityResult(int,int,Intent)
- String getFileExtension(Uri)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.celiacDay {
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
~ AlertDialog.Builder adb
~ AlertDialog ad
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
~ Toolbar toolbar
~ CountdownView countdownView
~ SimpleDateFormat sdf
~ String countDate
~ SliderView sliderView
~ int[] images
# void onCreate(Bundle)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.EndDrawerToggle {
- DrawerLayout drawerLayout
- AppCompatImageButton toggleButton
- int openDrawerContentDescRes
- int closeDrawerContentDescRes
- DrawerArrowDrawable arrowDrawable
+ <<Create>> EndDrawerToggle(DrawerLayout,Toolbar,int,int)
+ void syncState()
+ void onConfigurationChanged(Configuration)
+ void onDrawerSlide(View,float)
+ void onDrawerOpened(View)
+ void onDrawerClosed(View)
+ void onDrawerStateChanged(int)
- void loadDrawerArrowDrawable()
- void toggle()
- void setPosition(float)
- void setContentDescription(int)
}
class com.example.glutenfree.Login {
~ TextInputEditText Email
~ Button button
~ String email
~ CheckBox checkbox
~ FirebaseAuth Auth
~ FirebaseDatabase firebaseDatabase
~ DatabaseReference databaseReference
~ Toolbar toolbar
~ AlertDialog.Builder adb
~ AlertDialog ad
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
~ check_Input check
# void onCreate(Bundle)
+ void onClick(View)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.Restaurants {
# void onCreate(Bundle)
}
class com.example.glutenfree.Registration {
~ TextInputEditText FirstName
~ Switch profileType
~ Button button
~ FirebaseAuth firebaseAuth
~ FirebaseDatabase firebaseDatabase
~ ProgressDialog p
~ DatabaseReference databaseReference
~ String firstname
~ Toolbar toolbar
~ AlertDialog.Builder adb
~ AlertDialog ad
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
~ check_Input check
# void onCreate(Bundle)
+ void onClick(View)
+ void onComplete(Task<AuthResult>)
+ void onFailure(Exception)
+ void createUser()
- boolean isValidate()
+ void onSuccess(UploadTask.TaskSnapshot)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.bakeries {
~ TextView textFilter
~ Button search
~ Spinner filter
~ String chosen
~ Spinner cities
~ ArrayList<String> list1
~ ArrayList<String> list2
~ ArrayList<String> businessFilter
~ AlertDialog.Builder adb
~ AlertDialog ad
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
~ Toolbar toolbar
~ ArrayList<business> businesses
~ ArrayList<business> byCity
~ ArrayList<business> byDelivery
~ ArrayList<business> byBoth
~ FirebaseDatabase firebaseDatabase
~ DatabaseReference databaseReference
- List<CityData> CityDataread
# void onCreate(Bundle)
+ void onClick(View)
- void readCityData()
+ void onItemSelected(AdapterView<?>,View,int,long)
+ void onNothingSelected(AdapterView<?>)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.MainActivity {
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
~ AlertDialog.Builder adb
~ AlertDialog ad
~ Toolbar toolbar
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
# void onCreate(Bundle)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.videos {
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
~ AlertDialog.Builder adb
~ AlertDialog ad
~ Toolbar toolbar
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
# void onCreate(Bundle)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.Shops {
# void onCreate(Bundle)
}
class com.example.glutenfree.SliderAdapter {
~ ArrayList<Uri> images
~ Context context
+ <<Create>> SliderAdapter(ArrayList<Uri>,Context)
+ Holder onCreateViewHolder(ViewGroup)
+ void onBindViewHolder(Holder,int)
+ int getCount()
}
class com.example.glutenfree.SliderAdapter.Holder {
~ ImageView imageView
+ <<Create>> Holder(View)
}
class com.example.glutenfree.information {
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
~ AlertDialog.Builder adb
~ AlertDialog ad
~ Toolbar toolbar
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
# void onCreate(Bundle)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.links {
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
~ AlertDialog.Builder adb
~ AlertDialog ad
~ Toolbar toolbar
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
~ ImageView link1
# void onCreate(Bundle)
+ void onClick(View)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.addBusiness {
~ TextView textType
~ String chosen
~ Spinner spinner
~ ArrayList<String> businessType
~ Switch isDelivering
~ String Delivering
~ String Type
~ TextInputLayout shippingServices
~ TextInputEditText businessName
~ Button picturesPicker
~ ArrayList<String> StringPictures
~ ArrayList<Uri> UriPictures
~ FirebaseDatabase firebaseDatabase
~ ProgressDialog p
~ DatabaseReference databaseReference
~ StorageReference storageReference
~ SharedPreferences sharedPreferences
~ SharedPreferences.Editor editor
~ AlertDialog.Builder adb
~ AlertDialog ad
~ Toolbar toolbar
+ DrawerLayout drawerLayout
+ EndDrawerToggle drawerToggle
~ NavigationView navigationView
~ check_Input check
# void onCreate(Bundle)
+ void onClick(View)
# void onActivityResult(int,int,Intent)
- String getFileExtension(Uri)
+ boolean onNavigationItemSelected(MenuItem)
# void onPostCreate(Bundle)
+ void onConfigurationChanged(Configuration)
# void onStart()
# void onStop()
}
class com.example.glutenfree.User {
- String FirstName
- String LastName
- String Password
- String Email
- String ProfileImage
- String key
- String profileType
+ <<Create>> User(String,String,String,String,String,String,String)
+ <<Create>> User()
+ String getFirstName()
+ void setFirstName(String)
+ String getLastName()
+ void setLastName(String)
+ String getPassword()
+ void setPassword(String)
+ String getEmail()
+ void setEmail(String)
+ String getProfileImage()
+ void setProfileImage(String)
+ String getKey()
+ void setKey(String)
+ String getProfileType()
+ void setProfileType(String)
+ String toString()
}
class com.example.glutenfree.SliderAdapter2 {
~ int[] images
+ <<Create>> SliderAdapter2(int[])
+ SliderAdapter.Holder onCreateViewHolder(ViewGroup)
+ void onBindViewHolder(SliderAdapter.Holder,int)
+ int getCount()
}
class com.example.glutenfree.SliderAdapter2.Holder {
~ ImageView imageView
+ <<Create>> Holder(View)
}
class com.example.glutenfree.Splash {
~ Animation animationFadeIn
~ ImageView imageView
# void onCreate(Bundle)
}
class com.example.glutenfree.check_Input {
- String isnot
- Context context
- TextInputEditText inputEditText
+ <<Create>> check_Input(Context)
+ void setInputEditText(TextInputEditText)
+ boolean checkName(String)
+ boolean checkPass(String)
+ boolean checkMail(String)
+ boolean checkBusinessName(String)
+ boolean checkBusinessDescription(String)
+ boolean checkBusinessAddress(String)
+ boolean checkOpeningHours(String)
+ boolean checkPhone(String)
+ String toString()
}


android.content.BroadcastReceiver <|-- com.example.glutenfree.WifiReceiver
com.example.glutenfree.Adapter <|-- com.example.glutenfree.businessAdapter
com.example.glutenfree.businessAdapter +.. com.example.glutenfree.businessAdapter.viewHolder
com.example.glutenfree.ViewHolder <|-- com.example.glutenfree.businessAdapter.viewHolder
com.example.glutenfree.OnClickListener <|.. com.example.glutenfree.UpdateUser
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.UpdateUser
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.UpdateUser
com.example.glutenfree.OnClickListener <|.. com.example.glutenfree.Profile
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.Profile
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.Profile
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.celiacDay
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.celiacDay
com.example.glutenfree.DrawerListener <|.. com.example.glutenfree.EndDrawerToggle
com.example.glutenfree.OnClickListener <|.. com.example.glutenfree.Login
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.Login
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.Login
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.Restaurants
com.example.glutenfree.OnClickListener <|.. com.example.glutenfree.Registration
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.Registration
com.google.android.gms.tasks.OnCompleteListener <|.. com.example.glutenfree.Registration
com.google.android.gms.tasks.OnFailureListener <|.. com.example.glutenfree.Registration
com.google.android.gms.tasks.OnSuccessListener <|.. com.example.glutenfree.Registration
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.Registration
com.example.glutenfree.OnClickListener <|.. com.example.glutenfree.bakeries
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.bakeries
com.example.glutenfree.OnItemSelectedListener <|.. com.example.glutenfree.bakeries
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.bakeries
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.MainActivity
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.videos
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.videos
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.Shops
com.smarteist.autoimageslider.SliderViewAdapter <|-- com.example.glutenfree.SliderAdapter
com.example.glutenfree.SliderAdapter +.. com.example.glutenfree.SliderAdapter.Holder
com.example.glutenfree.ViewHolder <|-- com.example.glutenfree.SliderAdapter.Holder
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.information
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.information
com.example.glutenfree.OnClickListener <|.. com.example.glutenfree.links
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.links
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.links
com.example.glutenfree.OnClickListener <|.. com.example.glutenfree.addBusiness
com.example.glutenfree.OnNavigationItemSelectedListener <|.. com.example.glutenfree.addBusiness
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.addBusiness
com.smarteist.autoimageslider.SliderViewAdapter <|-- com.example.glutenfree.SliderAdapter2
com.example.glutenfree.SliderAdapter2 +.. com.example.glutenfree.SliderAdapter2.Holder
com.example.glutenfree.ViewHolder <|-- com.example.glutenfree.SliderAdapter2.Holder
androidx.appcompat.app.AppCompatActivity <|-- com.example.glutenfree.Splash
@enduml